-- Migration retained as a historical no-op.
-- Operational staff and banking records must never be committed to source control.
-- Import private staff data after deployment with:
-- node scripts/register-company-staff.mjs --input <private-json-path> --apply
