-- Production history marker only.
-- The original Production migration is superseded by the replay-safe
-- 20260722210000_optimize_rls_auth_initplan.sql migration.
-- Intentionally no-op: the canonical migration is the clean-replay source.
