-- Production history marker only.
-- The original Production migration is superseded by the replay-safe
-- 20260722224500_block_profile_privilege_escalation.sql migration.
-- Intentionally no-op: the canonical migration is the clean-replay source.
