-- Production history marker only.
-- The original Production migration is superseded by the replay-safe
-- 20260722204500_core_foreign_key_indexes.sql migration.
-- Intentionally no-op: the canonical migration fixes the SQL delimiter.
